default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: movie_catalog
  password: "122520Am"

development:
  <<: *default
  database: catalogo_filmes_development

test:
  <<: *default
  database: catalogo_filmes_test

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
